### ISSUE TITLE
Noob questions

### ISSUE THREAD

**Issue by snd977** [breadwallet/breadwallet#10]
I've read great things about breadwallet and am considering using it as my primary wallet.

A question for the paranoid: if, for whatever reason, the breadwallet app got pulled from the iTunes store, is there another way to recover your wallet?

The latest app update was released on 27 September 2014. When can we expect the next update to be available for download?

**Comment by voisine** [comment]
Next update is coming in a few weeks.

And yes, there are a few different options if the app were to be pulled. There are other wallets like hive that are available on other platforms, as well as web tools, and you could even build breadwallet from source using Xcode and run it in the iPhone simulator on your desktop.

**Comment by voisine** [comment]
new update is out.
