### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ScrambleKid** [breadwallet/breadwallet#11]
Hi

Bread has started crashing on my iPhone today. It just shows the splash screen for a few seconds and then crashes out. 

I have tried restarting the device, but don't want to reinstall the app as I'm nervous about wallet restores. 

iOS 8.1.2 on 5s

**Comment by voisine** [comment]
Sorry this is happening.

Did you by chance recently send or receive a lot of transactions in a row?

**Comment by ScrambleKid** [comment]
No. I actually hadn't done anything but update my balance for weeks.

**Comment by voisine** [comment]
If you email support@breadwallet.com with your phone's UDID, we can build a debug version of the app to help fix the problem.

You can get the UDID by connecting your phone to iTunes, clicking the phone icon, summary, then clicking the serial number. The serial number will switch to show the UDID.

**Comment by ScrambleKid** [comment]
HI Aaron

I've reinstalled Bread Wallet and it's working perfectly again. Thanks for
the responsiveness though. Awesome ;)

I was reluctant to reinstall because I didn't want to do unnecessary
passphrase restores, but thankfully app data was retained.

**Comment by voisine** [comment]
glad we got it working. new update has some crash fixes as well.
