### ISSUE TITLE
not synching?

### ISSUE THREAD

**Issue by nybe** [breadwallet/breadwallet#12]
Hi, been using bread wallet since your release. Today, now that I need to really access some coins, it will NOT synch, just sits at 6% and does nothing. 

PLEASE HELP

EDIT: I've tried rescanning blockchain a few times and it gets stuck at 6%

**Comment by voisine** [comment]
There are some bitcoin nodes on the network that are slow syncing and causing issues. The easiest way to to fix it right now is to delete and reinstall the app. (your wallet will automatically be re-created). I have an update coming out shortly that detects the problem and avoids those bitcoin nodes.

**Comment by nybe** [comment]
ok cool. thanks for the info

**Comment by voisine** [comment]
new update is out that fixes this

**Comment by nybe** [comment]
excellent! 

I truly dig your wallet and use it everyday. I am looking forward to it’s evolution, keep up the good work.

//Bob
