### ISSUE TITLE
Add option to show balance as BTC instead of bits

### ISSUE THREAD

**Issue by Rudayb23** [breadwallet/breadwallet#15]
Hello,
I love the simplicity of the app, but I would love the ability to change how I view my balance. I much rather see my balance as BTC instead of bits. Also I love the implementation of Touch ID. I think the app would be better if you had to use touch ID to get into the app and again when you try to send someone bitcoin.

Thank you,
Rudy Bermudez

**Comment by voisine** [comment]
Thanks for the feedback @Rudayb23. As I'm sure you noticed, touch id is now implemented.

We feel strongly that the community needs to move together to the 'bits' standard. I know that no one likes change, but the most important consideration is that everyone use the same denomination and we never have to change it again. If long time bitcoiners stick with other denominations it will hurt bitcoin adoption by confusing new users. Bits has two decimal places like every other currency on the planet, and is much easier to understand and use for the billions of people who aren't yet using bitcoin. It will also still work fine even if bitcoin replaces all other currencies.
