### ISSUE TITLE
Touch ID is enabled but asks for passcode when making payment, not touch ID

### ISSUE THREAD

**Issue by Rudayb23** [breadwallet/breadwallet#16]
Touch ID is enabled but asks for passcode when making payment, not touch ID. How can I make the app use touch ID?

**Comment by voisine** [comment]
You have to enter your pin the first time you unlock, then touch id is enabled by default for the next 1,000,000bits (1bitcoin) of spending. Each time you hit the touch id spending limit, you have to enter your pin the next time.

**Comment by voisine** [comment]
The idea is protect against the fake finger attack being able to empty your entire wallet. You can also choose to set the touch id limit higher or lower, or turn it off in settings.

**Comment by Rudayb23** [comment]
That is perfect thank you!
