### ISSUE TITLE
Don't know the mnemonic device / account recovery phrase. 

### ISSUE THREAD

**Issue by ShadowsEchoes** [breadwallet/breadwallet#18]
When it came up on the screen I quickly got up to grab a piece of paper, when I got back my phone had gone to sleep and when I turned it back on it  had skipped past that part.

**Comment by voisine** [comment]
you can find it under settings. it hides it when the phone goes to sleep so it doesn't get exposed to the screenshot the operating system takes of sleeping apps for the task switcher, but it should probably reappear when foregrounding the app again during the wallet creation process. thanks for reporting the issue.

**Comment by voisine** [comment]
fixed
