### ISSUE TITLE
transaction is post-dated?

### ISSUE THREAD

**Issue by ditkachicago** [breadwallet/breadwallet#19]
I have 2 rather good size payments I sent from my wallet and the status says transaction is post-dated. can you please help explain what that means?

**Comment by ditkachicago** [comment]
they also say date 9/3 then 10/3/ then 10/11

**Comment by voisine** [comment]
Is your wallet fully synced? I think there may be a bug where unconfirmed transactions get marked as post-dated during a blockchain rescan. Let me know if the transactions don't confirm shortly.

**Comment by voisine** [comment]
fixed for next release
