### ISSUE TITLE
breadwallet

### ISSUE THREAD

**Issue by rachan808** [breadwallet/breadwallet#20]
I have lost some coins in a breadwallet transaction. Can anyone help me with this?

To start, who owes this wallet (which I am guessing is a cold storage wallet owned by some wallet service )? 
1FjkkZLDc8CyVjmvVPAruxbYZQ63bsXheJ

**Comment by voisine** [comment]
You will need to contact the owner of that address and request they return the funds. I have no way to tell who owns it. Did you copy the address from a previous transaction? If so, do you remember who the previous transaction was to?

**Comment by rachan808** [comment]
No, I sent you a private message on reddit, please check that message for more details about this problem. The scan was made by my bread wallet of his bread wallet qr code but he did not receive coins. Please refer to my private message for exact details on this transaction...I would really like to get this resolved. Thanks

**Comment by voisine** [comment]
Which reddit username did you message? I don't see it.

**Comment by rachan808** [comment]
Sorry, PM message was to you at bitcointalk 


Sent from Yahoo Mail on Android

**Comment by rachan808** [comment]
sorry. it was your username at bitcointalk

Sent from Yahoo Mail on Android

**Comment by rachan808** [comment]
I PM voisine

Further to my earlier email, please refer to my reddit PM message to you, which goes over what happened in exact detail.

Please I need you to bring your resources to bear on this as I really don't want to ask the Reddit community for help because it would not bring good PR for Breadwallet and I love my Breadwallet. 
My son writes : " I'm wondering if its not a bug in breadwallet"


Sent from Yahoo Mail on Android

**Comment by rachan808** [comment]
Here is the exact same thing that has happened to someone else, as posted on Reddit 11 hours ago. 
What's happening? .

A customer received a payment to his breadwallet and a new address was generated (qr code was scanned at a bitcoin ATM). The transaction shows on the blockchain but not in his wallet. He rescanned his breadwallet and nothing shows. He was able to to do a second transaction afterwards that went through fine. I suspect there may have been a misread of the qr code. Is there a way to retrieve and view all the used public bitcoin addresses in the breadwallet? We would like to compare those and see if there was one similar to the one where the bitcoins were sent.

Sent from Yahoo Mail on Android

**Comment by voisine** [comment]
I responded on bitcointalk.org, also do you have a link to the reddit post? Searching on reddit.com/r/bitcoin didn't come up with anything.

**Comment by rachan808** [comment]
http://www.reddit.com/r/breadwallet/comments/2zzf6q/how_can_i_view_my_used_public_addresses/
