### ISSUE TITLE
syncing VERY slow

### ISSUE THREAD

**Issue by masvil** [breadwallet/breadwallet#21]
It syncs VERY slow, sometimes hang. I have no connection problem.

**Comment by voisine** [comment]
What version of the app are you running? The latest version does a better job of detecting slow nodes, but it's still possible to connect to a slow one.

**Comment by masvil** [comment]
Last one, 0.5.
Tried to re-install, but nothing changed.
-- 
Massimo

Ciao Aaron,

in data domenica 12 aprile 2015, alle ore 22:15, hai scritto:

**Comment by voisine** [comment]
What country are located in? I wonder if we see better performance when connecting to random nodes since many are located in the U.S.

We could possibly prioritize nodes at IPs within your own country for better performance.

**Comment by masvil** [comment]
I'm in Italy. When I used it 2 months ago it was really fast, but now is unusable. I tried dozens of time: better case it took 100% in 20 minutes.
I'm available for every test.
-- 
Massimo

Ciao Aaron,

in data domenica 12 aprile 2015, alle ore 22:53, hai scritto:

**Comment by voisine** [comment]
That definitely isn't normal. Email me at support@breadwallet.com and we'll look into it. We can send you a debug version with extra logging to find out what's happening.

**Comment by masvil** [comment]
Tried 2 times but...

--- PASTE ---

Delivery to the following recipient failed permanently:

     support@breadwallet.com

Technical details of permanent failure: 
Google tried to deliver your message, but it was rejected by the server for the recipient domain breadwallet.com by aspmx.l.google.com. [2a00:1450:400c:c00::1b].

The error that the other server returned was:
550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1 http://support.google.com/mail/bin/answer.py?answer=6596 x4si14208411wjr.105 - gsmtp


----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=date:from:message-id:to:subject:in-reply-to:references:mime-version
         :content-type:content-transfer-encoding;
        bh=flBDuaCEsqbEHcCjUZxSHHIeiRZfEVnJ63Nu8aXKCiI=;
        b=xRTNrgzWouPk/tBj59iInrdtwrKM+/0Fjn8Z36P3tE7ea3VWw7OpMTGhbGRUv6lIZP
         rkPHtZyBJhG8QHfGf/F71kYRLg78Lbeufgj3mbh3cS9G/I47h95BMuAqKAQd1gZx/2pj
         ASSmHwj8Q+1/srXcNC/QGuJoFIq+3zZ0suu4p6zv1+wDhFYrJaw4qglLnTjrZif0MUKB
         xRBgKDHMAzy4En9lzVMEl4ypucySkG4tIK343ekqAYm4VpyjHi5cEVEru9dP4DdAKyVN
         tIpcsZVX2w5PVCao5Fzg/7aYpV60K0Y8vWhiTlKZov2s47PwvaniYx3ADAbzWagJlUz0
         WHWg==
X-Received: by 10.180.95.135 with SMTP id dk7mr15657454wib.64.1428874100847;
        Sun, 12 Apr 2015 14:28:20 -0700 (PDT)
Return-Path: <masvil@gmail.com>
Received: from MINI (2-226-248-190.ip183.fastwebnet.it. [2.226.248.190])
        by mx.google.com with ESMTPSA id k2sm8557051wix.4.2015.04.12.14.28.19
        for <support@breadwallet.com>
        (version=TLSv1 cipher=RC4-SHA bits=128/128);
        Sun, 12 Apr 2015 14:28:20 -0700 (PDT)
Date: Sun, 12 Apr 2015 23:28:23 +0200
From: Massimo Villa <masvil@gmail.com>
X-Priority: 3 (Normal)
Message-ID: <1045299895.20150412232823@gmail.com>
To: support@breadwallet.com
Subject: Re: [breadwallet] syncing VERY slow (#21)
In-Reply-To: <breadwallet/breadwallet/issues/21/92135612@github.com>
References: <breadwallet/breadwallet/issues/21@github.com> <breadwallet/breadwallet/issues/21/92135612@github.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Here I am.
-- 
Massimo

Ciao Aaron,

in data domenica 12 aprile 2015, alle ore 23:25, hai scritto:

> That definitely isn't normal. Email me at
> support@breadwallet.comand we'll look into it. We can send you a
> debug version with extra logging to find out what's happening.
> —
> Reply to this email directly or view it on GitHub.
>   

-- 
Massimo

Ciao Aaron,

in data domenica 12 aprile 2015, alle ore 23:25, hai scritto:

**Comment by voisine** [comment]
sorry about that... just setup the support email the other day and didn't have it configured right. try it now.

**Comment by masvil** [comment]
Done. Now no errors :)
-- 
Massimo

Ciao Aaron,

in data lunedì 13 aprile 2015, alle ore 01:03, hai scritto:

**Comment by voisine** [comment]
user reports problem went away... let me know if it comes back
