### ISSUE TITLE
can you please add some more currencies 

### ISSUE THREAD

**Issue by superyona** [breadwallet/breadwallet#22]
hi, i am an ambassador in the bitcoin embassy in Tel Aviv, we really like your app. People come by and we suggest it to them all the time... the only problem is that they wish it could work like mycelium and use our local currency [ILS] so they could use it for day to day stuff

**Comment by voisine** [comment]
Thank you, the next update uses bitpay.com/rates for exchange data, which includes ILS and many more, even gold and silver. Also, we have a crowdin.com project up to translate breadwallet into other languages. If you have anyone who would be willing to do the Hebrew and possibly also Arabic translations we'd appreciate the help! https://crowdin.com/project/breadwallet
