### ISSUE TITLE
People flock from breadwallet because of low fees

### ISSUE THREAD

**Issue by keo** [breadwallet/breadwallet#27]
Hi,

we're running an ATM and an online exchange and again we have a great influx of support requests because people can't cash out.

Here's an example support request: "So I got my BTC now in the breadwallet, is there any way to move it quickly out of that wallet to a wallet where I can set fees?"

We need 1 confirmation for the ATM to give out cash above 100 EUR. And there is a 6 hour time window to do it.

When the network is congested, breadwallet users' transaction usually confirm in 8-16 hours, which means we have to do everything by hand for all these stuck transactions (giving them cash, covering on an exchange, doing bookkeeping, clearing the database, etc.)

**It would be great if there would be a way (somewhere deep and hidden in some kind of advanced settings)  to set a fee priority level.**

We're still recommending breadwallet to all our users because we love it but we're on the brink of looking for other alternatives as this has a huge load on our support staff.

Thank you for reconsidering.

**Comment by tanzeelrana** [comment]
if i reduce the priority level. can i save on the bitcoin network transaction fees?

**Comment by tanzeelrana** [comment]
I want to know which variables to change in the ios app to change the cost of transaction. I have tried changing TX_FEE_PER_KB but I dont understand why I'm unable to reduce the network fee. 

For example:

Amount: $1
network fee: $5.51

Amount: $100
network fee: $ 5.51
