### ISSUE TITLE
Unable to reset

### ISSUE THREAD

**Issue by koalalorenzo** [breadwallet/breadwallet#28]
Hello!
I have created a dummy wallet, with no money in it, after deleting my previous one. Since I was distracted I have not copied the mnemonic phrase. Now I can not reset the wallet, since it was not asking for a new PIN (not eve using my previous one). So now the wallet is locked.

How can I force-delete the wallet to generate a new one? I have tried to delete and re-install the app, but nothing changes. Any idea? 

I am using iOS 10.0.2 (latest available)

**Comment by voisine** [comment]
Hi @koalalorenzo, the main issue tracker is over github.com/voisine/breadwallet

I'm not quite sure I understand the issue with the PIN? If you didn't successfully enter and verify a PIN, then it is supposed to ask you to do that. If that's not the case, then it sounds like a bug.

If you entered a PIN and you just don't remember it, and you don't have the recovery phrase, you can continue to try different invalid PINs over the next 24hrs or so, and after you run out of attempts the wallet will be reset. (this is a safety feature so if you lend someone your phone, they can't wipe your wallet unless they have possession of it for a full day)

**Comment by koalalorenzo** [comment]
I don't recall inserting the PIN, but I don't remember that well, because I was doing it quickly.
Thanks for this info, I will just try again during the next 24h!
