### ISSUE TITLE
Cannot delete wallet or start a new one

### ISSUE THREAD

**Issue by intrig** [breadwallet/breadwallet#5]
When I set my iPhone down to write down the passcode, I accidentally pressed the button to continue.  Now I'm dead in the water.  Even deleting the app and reloading it doesn't start at the beginning.  And I cannot  start a new wallet without typing in the passcode of the current one.  

Doing a factory reset is not really an option for me.  

Perhaps deleting a wallet with 0 balance shouldn't require a factory reset.

**Comment by voisine** [comment]
new update is out that handles this better
